name: Lowest Number Test
on: [push]
jobs:
  lowest_number_test:
    name: Lowest Number Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v3
      with: 
        python-version: "3.13.2"
        
    - name: Produce Test 1 Output (10 numbers)
      run:  python3 find_lowest_number.py test_data/test1_input.txt test1_output.txt
    - name: Test 1
      run: diff test1_output.txt test_data/test1_expected.txt
      
    - name: Produce Test 2 Output (1 number)
      run:  python3 find_lowest_number.py test_data/test2_input.txt test2_output.txt
    - name: Test 2
      run: diff test2_output.txt test_data/test2_expected.txt
      
    - name: Produce Test 3 Output (no numbers)
      run:  python3 find_lowest_number.py test_data/test3_input.txt test3_output.txt
    - name: Test 3
      run: diff test3_output.txt test_data/test3_expected.txt
